### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by bmurray7** [bdauvergne/python-pkcs1#11]
Does this project use a specific open source license?

I would like to add the test vector requested in #10, but my employer only permits me to contribute to projects with a [permitted open source license](https://opensource.google/docs/patching/#patches-that-dont-require-any-review).

**Comment by bdauvergne** [comment]
License is MIT, it's written in the setup.py file and visible on pypi.

https://github.com/bdauvergne/python-pkcs1/blob/master/setup.py#L7
